
exec blueman-applet
exec nm-applet
exec trayscale --gapplication-service
exec flatpak run --user org.signal.Signal --start-in-tray
exec flatpak run --user dev.vencord.Vesktop --start-minimized
exec flatpak run --user com.github.zocker_160.SyncThingy --start-minimized
exec wl-paste --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec sway-autoname-workspaces.py
exec ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false




 exec swayidle -w \
          timeout 300 '/usr/bin/lock.sh' \
          timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
          before-sleep '/usr/bin/lock.sh'

# exec /usr/libexec/polkit-gnome-authentication-agent-1
exec /usr/libexec/lxqt-policykit-agent
exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway XCURSOR_THEME=$XCURSOR_THEME XCURSOR_SIZE=$XCURSOR_SIZE
exec systemd-notify --ready
exec /usr/bin/battery.sh

