
input type:touchpad {
    natural_scroll enabled
    tap enabled
    accel_profile "flat"
}

input type:mouse {
    accel_profile "flat"
}

input type:keyboard {
    xkb_layout us,es
    xkb_options grp:rctrl_toggle
}
