
input type:touchpad {
    natural_scroll enabled
    tap enabled
    accel_profile "flat"
    scroll_factor 0.3
}

input type:mouse {
    accel_profile "flat"
}

input type:keyboard {
    xkb_layout us,es
}
