for_window {
    [window_role="pop-up"] floating enable
    [window_role="bubble"] floating enable
    [window_role="dialog"] floating enable
    [window_type="dialog"] floating enable
    [app_id="otpclient"] floating enable
    [app_id="org.pulseaudio.pavucontrol"] floating enable
    [app_id="dev.deedles.Trayscale"] floating enable
    [app_id="com.gar.floating"] floating enable; move container position center
    [app_id="com.gar.wallpaper"] floating enable; move container position center
    [app_id="lxqt-policykit-agent"] floating enable; move container position center
    [app_id="imv"] floating enable
    # Don't sleep when an app is fullscreen
    [class="^.*"] inhibit_idle fullscreen
    [app_id="^.*"] inhibit_idle fullscreen
}
mouse_warping container
