for_window {
    [window_role="pop-up"] floating enable
    [window_role="bubble"] floating enable
    [window_role="dialog"] floating enable
    [window_type="dialog"] floating enable
    [app_id="otpclient"] floating enable
    [app_id="org.pulseaudio.pavucontrol"] floating enable
    [app_id="dev.deedles.Trayscale"] floating enable
    [app_id="com.gar.floating"] floating enable; move container position center
    [app_id="com.gar.wallpaper"] floating enable; move container position center
    [app_id="lxqt-policykit-agent"] floating enable; move container position center
    [app_id="imv"] floating enable
    # Don't sleep when an app is fullscreen
    [class="^.*"] inhibit_idle fullscreen
    [app_id="^.*"] inhibit_idle fullscreen

    # Workspaces, browser and term
    [app_id="zen"] move window to workspace number 1
    [app_id="com.mitchellh.ghostty"] move window to workspace number 2
    # chat apps
    [instance="signal"] move window to workspace number 4
    [instance="discord"] move window to workspace number 4
    # music
    [app_id="com.github.neithern.g4music"] move window to workspace number 5
    # vms
    [app_id="virt-manager"] move window to workspace number 6
    # gaming (steam)
    [class="steam"] move window to workspace number 7
}
# skibidi mouse movement
mouse_warping container
