
for_window [class="^.*"] inhibit_idle fullscreen
for_window [app_id="^.*"] inhibit_idle fullscreen

for_window [app_id="imv"] floating enable

for_window [app_id="lxqt-policykit-agent"] {
    floating enable
    move position center
}

for_window [app_id="com.gar.wallpaper"] {
    floating enable
    move container position center
}
for_window {
    [window_role="pop-up"] floating enable
    [window_role="bubble"] floating enable
    [window_role="dialog"] floating enable
    [window_type="dialog"] floating enable
    [app_id="otpclient"] floating enable
    [app_id="org.pulseaudio.pavucontrol"] floating enable
    [app_id="dev.deedles.Trayscale"] floating enable
}
mouse_warping container

# for_window [app_id="org.wezfurlong.wezterm"] floating toggle
# for_window [app_id="org.wezfurlong.wezterm"] floating toggle
