
# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
shell /usr/bin/fish
font OverpassMono Nerd Font Mono
#background_opacity         0.95
#dynamic_background_opacity yes
font_size 15
