theme = "carbonfox_transparent"

[editor]
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
line-number = "relative"
mouse = true
color-modes = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = false

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0

[keys.normal]
'z' = {'y'=':yank-diagnostic'}
' ' = {'l'=':o .github', 'W'=':wa', 'q'=':wqa', 'Q'=':q!'}
"ret" = "goto_word"
'L' = "move_next_sub_word_end"
'H' = "move_prev_sub_word_start"


# Vim-like jumping stuffs
# Match next inner pairs
[keys.normal.m.n.i]
"(" = "@s\\(<ret>nmim"
"{" = "@s\\{<ret>nmim"
"[" = "@s\\[<ret>nmim"
'"' = '@s\"<ret>nmim'
"'" = "@s\\'<ret>nmim"
"<" = "@s<lt><ret>nmim"

# Match next around pairs  
[keys.normal.m.n.a]

"(" = "@s\\(<ret>nmam"
"{" = "@s\\{<ret>nmam"
"[" = "@s\\[<ret>nmam"
'"' = '@s\"<ret>nmam'
"'" = "@s\\'<ret>nmam"
"<" = "@s<lt><ret>nmam"

# Match previous inner pairs
[keys.normal.m.p.i]
"(" = "@s\\)<ret>Nmmmim"
"{" = "@s\\}<ret>Nmmmim"
"[" = "@s\\]<ret>Nmmmim"
'"' = '@s\"<ret>Nmmmim'
"'" = "@s\\'<ret>Nmmmim"
"<" = "@s<gt><ret>Nmmmim"

# Match previous around pairs
[keys.normal.m.p.a]
"(" = "@s\\)<ret>Nmmmam"
"{" = "@s\\}<ret>Nmmmam"
"[" = "@s\\]<ret>Nmmmam"
'"' = '@s\"<ret>Nmmmam'
"'" = "@s\\'<ret>Nmmmam"
"<" = "@s<gt><ret>Nmmmam"
