# [language-server.godot]
# command = "nc" 
# args = [ "127.0.0.1", "6005"]

# [[language]]
# name = "gdscript"
# language-servers = [ "godot" ]

# [[language]]
# name = "python"
# language-servers = [ "pyright" ]

# [[language]]
# name = "markdown"
# language-servers = [ "markdown-oxide" ]

# [[language]]
# name = "haxe"
# scope = "source.haxe"
# injection-regex = "Haxe"
# file-types = ["hx"]
# roots = [ "build.hxml" ]
# indent = { tab-width = 4, unit = "    " }

[[language]]
name = "kconfig"
file-types = ["kconfig", "kconfig*."]
scope = "source.kconfig"
comment-token = "#"

[[grammar]]
name = "kconfig"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-kconfig" , rev = "9ac99fe4c0c27a35dc6f757cef534c646e944881" }


# [[language]]
# name = "batch"
# file-types = ["bat"]
# scope = "source.batch"

# [[grammar]]
# name = "batch"
# source = { git = "https://github.com/davidevofficial/tree-sitter-batch" , rev = "737a031b42240bf61bf7ea5e4356d4e0580dd6d9" }

[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onType", outputPath = "$root/$dir/$name" }

# [[grammar]]
# name = "haxe"
# source = { git = "https://github.com/gerblesh/tree-sitter-haxe" , rev = "try-catch-while-for-enum" }

# [language-server.ruby-lsp]
# command = "ruby-lsp"
# config = { diagnostics = true, formatting = true }

# [[language]]
# name = "ruby"
# language-servers = ["ruby-lsp"]
# auto-format = true
