tap "homebrew/bundle"
tap "homebrew/services"
tap "caarlos0/tap"
# Modern Unix
brew "caarlos0/tap/timer"
brew "bat"
brew "fd"
brew "eza"
brew "ripgrep"
brew "zoxide"
brew "slides"
brew "yazi"
brew "btop"
brew "butane"
brew "libqalculate"
brew "lazygit"
brew "fastfetch"
brew "scrcpy"
brew "chafa"
brew "imagemagick"
brew "helix"
brew "nushell"
brew "gdu"
brew "meson"
brew "netcat"

# Programming languages
brew "go"
brew "java"

# Dev tools
brew "hugo"
brew "nvim"
brew "luarocks"

# Backup
brew "chezmoi"      # Dotfile management
brew "rbw"          # Required for storing secrets in chezmoi

# Misc
brew "yt-dlp"   # Download anything from anywhere
brew "xdg-ninja", args: ["HEAD"] # Declutter your HOME
brew "tlrc"     # Man pages, but straight to the point
